# Generated by Django 5.1.15 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_bagtype_catalogpagecontent_and_more'),
    ]

    operations = [
        # Repair: 0003_ was previously deployed as an empty stub, so its tables
        # were never created in the DB even though it's marked as applied.
        # This RunSQL recreates them idempotently (IF NOT EXISTS is a no-op on
        # fresh databases where 0003_ ran correctly).
        migrations.RunSQL(
            sql="""
CREATE TABLE IF NOT EXISTS "core_aboutsection" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "lead_text" text NOT NULL,
    "lead_text_uk" text NULL,
    "lead_text_en" text NULL,
    "body_text" text NOT NULL,
    "body_text_uk" text NULL,
    "body_text_en" text NULL
);
CREATE TABLE IF NOT EXISTS "core_bagtype" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "description" text NOT NULL,
    "description_uk" text NULL,
    "description_en" text NULL,
    "icon_svg" text NOT NULL DEFAULT '',
    "feature_1" varchar(255) NOT NULL DEFAULT '',
    "feature_1_uk" varchar(255) NULL,
    "feature_1_en" varchar(255) NULL,
    "feature_2" varchar(255) NOT NULL DEFAULT '',
    "feature_2_uk" varchar(255) NULL,
    "feature_2_en" varchar(255) NULL,
    "feature_3" varchar(255) NOT NULL DEFAULT '',
    "feature_3_uk" varchar(255) NULL,
    "feature_3_en" varchar(255) NULL,
    "order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS "core_catalogpagecontent" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "description" text NOT NULL,
    "description_uk" text NULL,
    "description_en" text NULL,
    "cta_title" varchar(255) NOT NULL DEFAULT '',
    "cta_title_uk" varchar(255) NULL,
    "cta_title_en" varchar(255) NULL,
    "cta_description" text NOT NULL DEFAULT '',
    "cta_description_uk" text NULL,
    "cta_description_en" text NULL,
    "cta_button_text" varchar(100) NOT NULL DEFAULT '',
    "cta_button_text_uk" varchar(100) NULL,
    "cta_button_text_en" varchar(100) NULL
);
CREATE TABLE IF NOT EXISTS "core_contactsection" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "intro_text" text NOT NULL,
    "intro_text_uk" text NULL,
    "intro_text_en" text NULL
);
CREATE TABLE IF NOT EXISTS "core_flexosection" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "lead_text" text NOT NULL,
    "lead_text_uk" text NULL,
    "lead_text_en" text NULL,
    "body_text" text NOT NULL,
    "body_text_uk" text NULL,
    "body_text_en" text NULL,
    "cta_text" varchar(100) NOT NULL DEFAULT '',
    "cta_text_uk" varchar(100) NULL,
    "cta_text_en" varchar(100) NULL,
    "cta_url" varchar(500) NOT NULL DEFAULT '',
    "cta_url_uk" varchar(500) NULL,
    "cta_url_en" varchar(500) NULL
);
CREATE TABLE IF NOT EXISTS "core_herosection" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "eyebrow" varchar(255) NOT NULL DEFAULT '',
    "eyebrow_uk" varchar(255) NULL,
    "eyebrow_en" varchar(255) NULL,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "subtitle" text NOT NULL,
    "subtitle_uk" text NULL,
    "subtitle_en" text NULL,
    "background_image" varchar(255) NULL,
    "cta_primary_text" varchar(100) NOT NULL DEFAULT '',
    "cta_primary_text_uk" varchar(100) NULL,
    "cta_primary_text_en" varchar(100) NULL,
    "cta_primary_url" varchar(500) NOT NULL DEFAULT '',
    "cta_primary_url_uk" varchar(500) NULL,
    "cta_primary_url_en" varchar(500) NULL,
    "cta_secondary_text" varchar(100) NOT NULL DEFAULT '',
    "cta_secondary_text_uk" varchar(100) NULL,
    "cta_secondary_text_en" varchar(100) NULL,
    "cta_secondary_url" varchar(500) NOT NULL DEFAULT '',
    "cta_secondary_url_uk" varchar(500) NULL,
    "cta_secondary_url_en" varchar(500) NULL
);
CREATE TABLE IF NOT EXISTS "core_serviceitem" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "description" text NOT NULL,
    "description_uk" text NULL,
    "description_en" text NULL,
    "icon_svg" text NOT NULL DEFAULT '',
    "order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS "core_sitesettings" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "site_name" varchar(100) NOT NULL DEFAULT 'Magnum',
    "site_name_uk" varchar(100) NULL,
    "site_name_en" varchar(100) NULL,
    "tagline" varchar(255) NOT NULL DEFAULT 'Виробництво якісного пакування',
    "tagline_uk" varchar(255) NULL,
    "tagline_en" varchar(255) NULL,
    "copyright_text" varchar(255) NOT NULL DEFAULT 'Всі права захищені',
    "copyright_text_uk" varchar(255) NULL,
    "copyright_text_en" varchar(255) NULL,
    "logo" varchar(255) NULL,
    "favicon" varchar(255) NULL,
    "og_image" varchar(255) NULL,
    "default_meta_title" varchar(255) NOT NULL DEFAULT '',
    "default_meta_title_uk" varchar(255) NULL,
    "default_meta_title_en" varchar(255) NULL,
    "default_meta_description" text NOT NULL DEFAULT '',
    "default_meta_description_uk" text NULL,
    "default_meta_description_en" text NULL
);
CREATE TABLE IF NOT EXISTS "core_testimonial" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "name_uk" varchar(255) NULL,
    "name_en" varchar(255) NULL,
    "text" text NOT NULL,
    "text_uk" text NULL,
    "text_en" text NULL,
    "role" varchar(255) NOT NULL DEFAULT '',
    "role_uk" varchar(255) NULL,
    "role_en" varchar(255) NULL,
    "avatar" varchar(255) NULL,
    "order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS "core_aboutfeature" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "text" varchar(255) NOT NULL,
    "text_uk" varchar(255) NULL,
    "text_en" varchar(255) NULL,
    "order" integer NOT NULL DEFAULT 0,
    "about_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "core_aboutstat" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "value" varchar(100) NOT NULL,
    "value_uk" varchar(100) NULL,
    "value_en" varchar(100) NULL,
    "label" varchar(255) NOT NULL,
    "label_uk" varchar(255) NULL,
    "label_en" varchar(255) NULL,
    "order" integer NOT NULL DEFAULT 0,
    "about_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "core_flexobenefit" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "title_uk" varchar(255) NULL,
    "title_en" varchar(255) NULL,
    "text" text NOT NULL,
    "text_uk" text NULL,
    "text_en" text NULL,
    "icon_svg" text NOT NULL DEFAULT '',
    "order" integer NOT NULL DEFAULT 0,
    "flexo_id" bigint NOT NULL
);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='BagsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Типи пакетів',
                'verbose_name_plural': 'Секція — Типи пакетів',
            },
        ),
        migrations.CreateModel(
            name='CatalogPreviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('cta_button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки CTA')),
                ('cta_button_text_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки CTA')),
                ('cta_button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки CTA')),
            ],
            options={
                'verbose_name': 'Секція — Популярна продукція',
                'verbose_name_plural': 'Секція — Популярна продукція',
            },
        ),
        migrations.CreateModel(
            name='CurrencySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Курс валют',
                'verbose_name_plural': 'Секція — Курс валют',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Сервіси',
                'verbose_name_plural': 'Секція — Сервіси',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Відгуки',
                'verbose_name_plural': 'Секція — Відгуки',
            },
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(default='49102', max_length=20, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address_en',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address_uk',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, null=True, verbose_name='Вулиця'),
        ),
    ]
