# Generated by Django 5.1.15 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_bagtype_catalogpagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Типи пакетів',
                'verbose_name_plural': 'Секція — Типи пакетів',
            },
        ),
        migrations.CreateModel(
            name='CatalogPreviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('cta_button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки CTA')),
                ('cta_button_text_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки CTA')),
                ('cta_button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки CTA')),
            ],
            options={
                'verbose_name': 'Секція — Популярна продукція',
                'verbose_name_plural': 'Секція — Популярна продукція',
            },
        ),
        migrations.CreateModel(
            name='CurrencySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Курс валют',
                'verbose_name_plural': 'Секція — Курс валют',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок секції')),
                ('subtitle_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Підзаголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Сервіси',
                'verbose_name_plural': 'Секція — Сервіси',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секції')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секції')),
            ],
            options={
                'verbose_name': 'Секція — Відгуки',
                'verbose_name_plural': 'Секція — Відгуки',
            },
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Hero опис'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='hero_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='order_cta_text_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кнопка замовлення (товар)'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='product_desc_heading_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок опису товару'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='catalogpagecontent',
            name='related_heading_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок схожих товарів'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(default='49102', max_length=20, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address_en',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_address_uk',
            field=models.CharField(default='вул. Волинська, 46', max_length=255, null=True, verbose_name='Вулиця'),
        ),
    ]
